#端口地址
address=":8080"
#数据库账户
username="root"
#密码
password=""
#注册密码salt
pass_salt="dawndevil"
#登录salt
login_salt="dawndevil"
#服务器生成的session对应cookie名称
session_name="media_web"
#头像目录
avatar_dir="static/media/avatar/"
#头像网址
avatar_map="/static/media/avatar/"
#封面目录
cover_dir="static/media/cover/"
#封面网址
cover_map="/static/media/cover/"
#媒体目录
media_dir="static/media/video/"
#媒体网址
media_map="/static/media/video/"
